spring.application.name=checkit
spring.security.oauth2.client.registration.google.client-id=${ID_CLIENTE}
spring.security.oauth2.client.registration.google.client-secret=${CLIENTE_SECRETO}
spring.security.oauth2.client.registration.google.scope=openid,profile,email,https://www.googleapis.com/auth/calendar
spring.security.oauth2.client.registration.google.redirect-uri={baseUrl}/login/oauth2/code/{registrationId}


