spring.application.name=checkit
spring:
    security:
        oauth2:
            client:
                registration:
                    google:
                        client-id: ${ID_CLIENTE}
                        client-secret: ${CLIENTE_SECRETO}
                        scope:
                            openid
                            profile
                            email
                            https:// encontrar calendar api